- client/src/pages/Student/JoinRoom/JoinRoom.tsx
- client/src/pages/Teacher/ManageRoom/ManageRoom.tsx
> Fix user join room bug

- client/src/components/Questions/MultipleChoiceQuestion/MultipleChoiceQuestion.tsx
- client/src/components/Questions/NumericalQuestion/NumericalQuestion.tsx
- client/src/components/Questions/Question.tsx
- client/src/components/Questions/ShortAnswerQuestion/ShortAnswerQuestion.tsx
- client/src/components/Questions/TrueFalseQuestion/TrueFalseQuestion.tsx
- client/src/components/Questions/questionStyle.css
Modification de comment les questions sont affichées, en particulier pour le positionnement des formules mathématiques. Les titres sont maintenant affichable et n'apparaissent pas pour le moment s'ils sont absents (null). Code révisé sur WEB
> Modification affichage latex et titres

- docker-compose.yaml
> Proposed edit in update schedule

- client/src/components/GIFTCheatSheet/GiftCheatSheet.tsx
- client/src/components/GiftTemplate/templates/TextType.ts
- client/src/components/Questions/MultipleChoiceQuestion/MultipleChoiceQuestion.tsx
- client/src/components/Questions/NumericalQuestion/NumericalQuestion.tsx
- client/src/components/Questions/Question.tsx
- client/src/components/Questions/ShortAnswerQuestion/ShortAnswerQuestion.tsx
- client/src/components/Questions/TrueFalseQuestion/TrueFalseQuestion.tsx
- rapport/H24-iteration2.md
- Modification de la prise en charge des formules dans l'affichage des quiz
- Ajout de la prise en charge de markdown et les formules sur une ligne
- Correction du bug de sélection qui reste dans les quizs à choix de réponse
> Melanie ite4

- client/src/components/GiftTemplate/templates/TextType.ts
Fixes #84 Affichage des matrice problématique : ajout de '&' entre les éléments. #71
> Utilisation de > dans mathjax ne fonctionne pas

- client/src/pages/Teacher/Dashboard/Dashboard.tsx
> Quiz exporté n'est pas du GIFT valide

- .github/workflows/create-branch-images.yml
- auth_config.json
- docker-compose.yaml
- server/app.js
- server/config/auth.js
- server/controllers/auth.js
- server/routers/auth.js
#124 
#123 
#122 
Ajout d'un fichier de configuration d'authentification en json.
Le fichier est monté sur l'image backend dans le fichier docker-compose.
La configuration est récupérée sur le backend et une route pour informer le frontend des authentifications disponible a été créée.
> Configuration authentification - docker-compose

- client/src/pages/Student/JoinRoom/JoinRoom.tsx
> Nom de la salle devrait être en premier sur /student/join-room

- .github/workflows/create-branch-images.yml
fixes ets-cfuhrman-pfe/EvalueTonSavoir#104
> Create branch images to facilitate production and tests deployment

- .github/workflows/create-branch-images.yml
Don't create branch images when pushes to main
> Don't create branch images when pushing to main

- client/src/App.tsx
- client/src/components/Header/Header.tsx
- client/src/pages/AuthSelection/AuthCallback.tsx
- client/src/pages/AuthSelection/AuthSelection.tsx
- client/src/pages/AuthSelection/SimpleLogin.tsx
- client/src/pages/Home/Home.tsx
- client/src/services/ApiService.tsx
- docker-compose.yaml
- server/app.js
- server/auth/modules/passport-providers/oauth.js
- server/auth/modules/passport-providers/oidc.js
- server/auth/modules/passportjs.js
- server/config/auth.js
- server/models/authProvider.js
- server/models/authUserAssociation.js
- server/models/userAuthAssociation.js
- server/models/users.js
- server/utils.js
Adds to devs branch to do docker image
> Modularise auth methods

- .github/workflows/create-branch-images.yml
Probleme : 
- L'image genere contenais les trois services ensemble, empêchant le deploiement de chaque partie. (extraction de metadata)
Fix :
- Separation en 3 builds distinct avec un extraction distincte
- Testée mon serveur privé et fonctionnel ( Image directement prise de GHRC sans problème )
- Regle un probleme avec l'encodage des caracteres dans le nom des images ( utiliser / peut causer des problemes avec l'api)
Suggestion additionnelles : 
Supprimer toutes les images creer avec l'ancienne methode
> Fixes images

- client/src/App.tsx
- client/src/pages/AuthManager/callback/AuthCallback.tsx
- client/src/pages/Student/JoinRoom/JoinRoom.tsx
- client/src/services/ApiService.tsx
- docker-compose.yaml
- server/.env.example
- server/__tests__/auth.test.js
- server/auth/auth-manager.js
- server/config/auth.js
- server/controllers/auth.js
- server/routers/auth.js
Adds a route to inform the frontend it can let (or not ) anonymous users to log on the join-room page.
(Needs modifications to handle this as better solution)
> Adds (no) authentication requirement to join a room

- client/src/pages/Teacher/EditorQuiz/editorQuiz.css
> Ajustement de l'interface problématique dans l'éditeur de quiz

- client/src/components/Questions/MultipleChoiceQuestion/MultipleChoiceQuestion.tsx
> LaTeX mal affichée quand on lance le quiz (mais ok en Prévisualisation)

- server/models/images.js
> Impossible de téleverser une image (Erreur 505)

- client/package-lock.json
- client/package.json
- client/src/__tests__/components/GiftTemplate/templates/AnswerIcon.test.tsx
- client/src/components/GiftTemplate/GIFTTemplatePreview.tsx
- client/src/components/Questions/MultipleChoiceQuestion/MultipleChoiceQuestion.tsx
- client/src/components/Questions/NumericalQuestion/NumericalQuestion.tsx
- client/src/components/Questions/ShortAnswerQuestion/ShortAnswerQuestion.tsx
- client/src/components/Questions/TrueFalseQuestion/TrueFalseQuestion.tsx
- package-lock.json
- package.json
Fixes #192
DOMPurify was added and all html got sanitized
> Risques sécurité dangerouslySetInnerHTML()

- client/src/components/GIFTCheatSheet/GiftCheatSheet.tsx
- client/src/pages/Teacher/EditorQuiz/EditorQuiz.tsx
> Ce n'est pas évident que le format [markdown] doit être utilisé pour les images

- client/src/__tests__/components/QuestionsDisplay/MultipleChoiceQuestionDisplay/MultipleChoiceQuestionDisplay.test.tsx
- client/src/__tests__/components/QuestionsDisplay/TrueFalseQuestionDisplay/TrueFalseQuestionDisplay.test.tsx
- client/src/components/QuestionsDisplay/MultipleChoiceQuestionDisplay/MultipleChoiceQuestionDisplay.tsx
- client/src/components/QuestionsDisplay/TrueFalseQuestionDisplay/TrueFalseQuestionDisplay.tsx
- server/package-lock.json
> L'affichage de la bonne réponse dans les rétroactions ne fonctionne plus

- client/src/components/QuestionsDisplay/questionStyle.css
> Problème dans l'affichage des rétroactions  Katek pour les prévisualisations (Éditeur de quiz)

- client/src/components/QuestionsDisplay/questionStyle.css
> Problème dans l'affichage des rétroactions  Katek pour les questions réponses courtes et numériques

- client/src/__tests__/components/LiveResults/LiveResults.test.tsx
- client/src/components/LiveResults/LiveResults.tsx
> [Katex] La L'affichage du tableau AVEC réponses pose problème lorsqu'il y a des équations

- client/src/components/TeacherModeQuiz/TeacherModeQuiz.tsx
> [Rythme enseignant] Fenêtre de rétroaction reste ouverte pour les prochaines questions si l'étudiant ne l'enlève pas

- client/src/components/GiftTemplate/GIFTTemplatePreview.tsx
- client/src/components/GiftTemplate/templates/TextTypeTemplate.ts
- client/src/components/LiveResults/LiveResults.tsx
> Faire l'appel de TextTypeTemplate au lieu de format() et sanitize()

- client/src/components/GiftTemplate/templates/TextTypeTemplate.ts
> Erreur lors de la création d'un quiz en cours d'édition avec l'utilisation du \

- client/src/components/GIFTCheatSheet/GiftCheatSheet.tsx
> Ajuster les modèles de questions de l'éditeur et corriger une possible erreur

- client/package-lock.json
- client/src/__tests__/pages/Student/TeacherModeQuiz/TeacherModeQuiz.test.tsx
- client/src/components/GiftTemplate/GIFTTemplatePreview.tsx
- client/src/components/GiftTemplate/templates/TextTypeTemplate.ts
- client/src/components/LiveResults/LiveResults.tsx
- client/src/components/TeacherModeQuiz/TeacherModeQuiz.tsx
Fixes https://github.com/ets-cfuhrman-pfe/EvalueTonSavoir/issues/230
> Les longues réponses dépassent le cadre de la fenêtre de rétroaction

- client/src/pages/Student/JoinRoom/JoinRoom.tsx
- client/src/pages/Teacher/Login/Login.tsx
> Touche retour équivaut à un clique sur le bouton

- client/Dockerfile
- client/src/pages/AuthManager/callback/AuthCallback.tsx
- client/src/pages/AuthManager/providers/SimpleLogin/Register.tsx
- docker-compose-local.yaml
- docker-compose.yaml
- server/auth/auth-manager.js
- server/auth/modules/passport-providers/oauth.js
- server/auth/modules/passport-providers/oidc.js
- server/auth/modules/passportjs.js
- server/auth/modules/simpleauth.js
- server/auth_config.json.example
- server/models/users.js
- server/package-lock.json
- server/package.json
- ajout du callback pour env prod
- ajout de simple auth 
- modification du model users
> Ajustement callback URI

- client/src/__tests__/pages/ManageRoom/ManageRoom.test.tsx
- client/src/pages/Teacher/ManageRoom/ManageRoom.tsx
- client/src/pages/Teacher/ManageRoom/manageRoom.css
**Contexte**  
En tant que professeur, je souhaite un bouton "Terminer le quiz" qui me permette de mettre fin à un quiz.
**Changements apportés dans cette PR**  
Ajout du bouton "Terminer le quiz" pour mettre fin au quiz.
> Ajout du bouton "Terminer le quiz"

- client/package-lock.json
- client/package.json
- client/src/__tests__/pages/ManageRoom/ManageRoom.test.tsx
- client/src/pages/Student/JoinRoom/JoinRoom.tsx
- client/src/pages/Teacher/ManageRoom/ManageRoom.tsx
- server/package-lock.json
- server/package.json
**Contexte**
En tant que professeur, je souhaite permettre à mes étudiants de rejoindre une salle unique déjà créée, facilement et rapidement, en scannant un code QR.
**Changements apportés dans cette PR**
Génération et affichage d'un code QR pour chaque salle existante
Permet aux étudiants de rejoindre la salle directement en scannant le code QR
> Rejoindre une salle via un code QR
